export const TRAIT_MODIFIERS = {
  // Ana özellik modifierleri (her olay tipi için)
  cesur: {
    SUCCESS: 2,
    FAILURE: -1,
    SOCIAL: 1,
    FINANCIAL: 0,
    INTERNAL: 0,
    IDEA: 1,
    CONFLICT: 2,
  },
  temkinli: {
    SUCCESS: -1,
    FAILURE: 1,
    SOCIAL: -1,
    FINANCIAL: 1,
    INTERNAL: 1,
    IDEA: 0,
    CONFLICT: -1,
  },
  yaratıcı: {
    SUCCESS: 1,
    FAILURE: 0,
    SOCIAL: 0,
    FINANCIAL: -1,
    INTERNAL: 1,
    IDEA: 3,
    CONFLICT: 0,
  },
  analitik: {
    SUCCESS: 1,
    FAILURE: 0,
    SOCIAL: -1,
    FINANCIAL: 2,
    INTERNAL: 0,
    IDEA: 2,
    CONFLICT: 0,
  },
  sosyal: {
    SUCCESS: 1,
    FAILURE: 0,
    SOCIAL: 3,
    FINANCIAL: 0,
    INTERNAL: -1,
    IDEA: 0,
    CONFLICT: 1,
  },
  içedönük: {
    SUCCESS: 0,
    FAILURE: 0,
    SOCIAL: -2,
    FINANCIAL: 0,
    INTERNAL: 3,
    IDEA: 1,
    CONFLICT: -1,
  },
  hırslı: {
    SUCCESS: 3,
    FAILURE: -2,
    SOCIAL: 0,
    FINANCIAL: 2,
    INTERNAL: -1,
    IDEA: 1,
    CONFLICT: 1,
  },
  mütevazı: {
    SUCCESS: 0,
    FAILURE: 1,
    SOCIAL: 1,
    FINANCIAL: -1,
    INTERNAL: 1,
    IDEA: 0,
    CONFLICT: -1,
  },
} as const;

export const WEAKNESS_MODIFIERS = {
  sabırsız: {
    SUCCESS: -1,
    FAILURE: 1,
    SOCIAL: 0,
    FINANCIAL: -1,
    INTERNAL: 1,
    IDEA: 0,
    CONFLICT: 1,
  },
  'aşırı düşünen': {
    SUCCESS: -1,
    FAILURE: 1,
    SOCIAL: 0,
    FINANCIAL: 0,
    INTERNAL: 2,
    IDEA: -1,
    CONFLICT: 1,
  },
  güvensiz: {
    SUCCESS: -2,
    FAILURE: 2,
    SOCIAL: -1,
    FINANCIAL: -1,
    INTERNAL: 1,
    IDEA: -1,
    CONFLICT: 1,
  },
  dağınık: {
    SUCCESS: -1,
    FAILURE: 1,
    SOCIAL: 0,
    FINANCIAL: -1,
    INTERNAL: 0,
    IDEA: 1,
    CONFLICT: 0,
  },
  bencil: {
    SUCCESS: 0,
    FAILURE: 0,
    SOCIAL: -2,
    FINANCIAL: 1,
    INTERNAL: -1,
    IDEA: 0,
    CONFLICT: 2,
  },
  inatçı: {
    SUCCESS: 0,
    FAILURE: 0,
    SOCIAL: -1,
    FINANCIAL: 0,
    INTERNAL: 0,
    IDEA: -1,
    CONFLICT: 2,
  },
  tembel: {
    SUCCESS: -2,
    FAILURE: 1,
    SOCIAL: 0,
    FINANCIAL: -1,
    INTERNAL: 0,
    IDEA: -1,
    CONFLICT: 0,
  },
} as const;

export const TALENT_MODIFIERS = {
  liderlik: {
    SUCCESS: 2,
    FAILURE: 0,
    SOCIAL: 2,
    FINANCIAL: 1,
    INTERNAL: 0,
    IDEA: 1,
    CONFLICT: 1,
  },
  sanat: {
    SUCCESS: 1,
    FAILURE: 0,
    SOCIAL: 1,
    FINANCIAL: -1,
    INTERNAL: 2,
    IDEA: 3,
    CONFLICT: 0,
  },
  spor: {
    SUCCESS: 2,
    FAILURE: 0,
    SOCIAL: 1,
    FINANCIAL: 0,
    INTERNAL: 1,
    IDEA: 0,
    CONFLICT: 1,
  },
  müzik: {
    SUCCESS: 1,
    FAILURE: 0,
    SOCIAL: 1,
    FINANCIAL: 0,
    INTERNAL: 2,
    IDEA: 2,
    CONFLICT: 0,
  },
  teknoloji: {
    SUCCESS: 2,
    FAILURE: 0,
    SOCIAL: -1,
    FINANCIAL: 2,
    INTERNAL: 0,
    IDEA: 3,
    CONFLICT: 0,
  },
  iletişim: {
    SUCCESS: 1,
    FAILURE: 0,
    SOCIAL: 3,
    FINANCIAL: 1,
    INTERNAL: 0,
    IDEA: 1,
    CONFLICT: -1,
  },
  'problem çözme': {
    SUCCESS: 2,
    FAILURE: 0,
    SOCIAL: 0,
    FINANCIAL: 1,
    INTERNAL: 1,
    IDEA: 2,
    CONFLICT: 1,
  },
  empati: {
    SUCCESS: 0,
    FAILURE: 0,
    SOCIAL: 3,
    FINANCIAL: 0,
    INTERNAL: 2,
    IDEA: 1,
    CONFLICT: -2,
  },
} as const;

export const EVENT_BASE_IMPACT = {
  SUCCESS: 50,
  FAILURE: -40,
  SOCIAL: 20,
  FINANCIAL: 30,
  INTERNAL: 10,
  IDEA: 25,
  CONFLICT: -30,
} as const;

export const PRIME_NUMBER = 997; // Deterministik dağılım için asal sayı

export const EVENT_TYPES = [
  'SUCCESS',
  'FAILURE',
  'SOCIAL',
  'FINANCIAL',
  'INTERNAL',
  'IDEA',
  'CONFLICT',
] as const;
